[package]
name = "amaru-ouroboros"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
hex.workspace = true
kes-summed-ed25519.workspace = true
pallas-codec.workspace = true
pallas-crypto.workspace = true
pallas-math.workspace = true
pallas-network.workspace = true
pallas-primitives.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
vrf_dalek.workspace = true

[dev-dependencies]
ctor.workspace = true
insta = { workspace = true, features = ["yaml"] }
pallas-traverse.workspace = true
tracing-subscriber.workspace = true
criterion.workspace = true
rand.workspace = true
serde_json.workspace = true

[[bench]]
harness = false
name = "benchmark"
